#!/usr/bin/env bash
# Generate version.h from git, then build. This is the ONLY supported build
# entry point: building in the Arduino IDE skips version generation, and a
# firmware with no version is exactly the blind spot OTA cannot tolerate.
set -euo pipefail
SKETCH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VER="$(git -C "$SKETCH_DIR" describe --tags --always --dirty 2>/dev/null || echo unknown)"
cat > "$SKETCH_DIR/version.h" <<EOF
// GENERATED by tools/build.sh -- do not edit, do not commit.
#pragma once
#define FW_VERSION "$VER"
EOF
echo "FW_VERSION = $VER"
arduino-cli compile --fqbn arduino:mbed_opta:opta "$SKETCH_DIR" "$@"
